groups:
- name: alert.rules
  rules:
  - alert: high_cpu_load
    expr: node_load1 >  95
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "alert from docker-prometheus: Server under high load  {{ $labels.group }}"
      description: "Cpu host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}  {{ $labels.group }}"

  - alert: EndpointDown
    expr: probe_success == 0
    for: 5m
    labels:
      severity: "critical"
    annotations:
      summary: "alert from docker-prometheus: Endpoint {{ $labels.instance }} down - {{ $labels.group }}  {{ $labels.group }} {{ $labels.env }}"

#Alert for any instance that has a median request latency >1s.
  - alert: APIHighRequestLatency
    expr: api_http_request_latencies_second{quantile="0.5"} > 1
    for: 10m
    annotations:
      summary: "alert from docker-prometheus: High request latency on {{ $labels.instance }}  {{ $labels.group }}"
      description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)  {{ $labels.group }}"


  - alert: high_memory_load
    expr: (sum(node_memory_MemTotal) - sum(node_memory_MemFree + node_memory_Buffers + node_memory_Cached)) / sum(node_memory_MemTotal) * 100 > 95
    for: 5m
    labels:
      severity: warning
    annotations:
      description: "Server host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}  {{ $labels.group }}"
      summary: "alert from docker-prometheus: Server memory is almost full  {{ $labels.group }}"


  - alert: high_storage_load
    expr: (node_filesystem_size{fstype="aufs"} - node_filesystem_free{fstype="aufs"})
      / node_filesystem_size{fstype="aufs"} * 100 > 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: Server storage usage is {{ humanize $value}}%. Reported by
        instance {{ $labels.instance }} of job {{ $labels.job }} - {{ $labels.group }}.
      summary: Server storage is almost full  {{ $labels.group }}


  - alert: high_disk_usage_linux
    expr: node_filesystem_free_bytes / node_filesystem_size_bytes * 100  < 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "alert from docker-prometheus: Instance {{ $labels.instance }} is low on disk space"
      description: "{{ $labels.instance }} has only {{ $value }}% free."

  - alert: high_node_memory_usage
    expr: (( node_memory_MemTotal_bytes - node_memory_MemFree_bytes  -  node_memory_Cached_bytes ) /  node_memory_MemTotal_bytes) * 100 > 95
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "alert from docker-prometheus: {{$labels.instance}}: High memory usage detected"
      description: "{{$labels.instance}}: Memory usage is above 90% (current value is: {{ $value }})"

  - alert: high_swap_node_memory_usage
    expr: (((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes ) / node_memory_SwapTotal_bytes ) *100 ) > 95
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "alert from docker-prometheus: {{$labels.instance}}: High swap memory usage detected"
      description: "{{$labels.instance}}: Swap Memory usage is above 95% (current value is: {{ $value }})"

  - alert: high_memory_load_windows
    expr: (wmi_os_physical_memory_free_bytes / wmi_cs_physical_memory_bytes) *100 < 5
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "alert from docker-prometheus: {{$labels.instance}}: High memory load detected"
      description: "{{$labels.instance}}: Memory load is above 95% (available memory on the server is: {{ $value }})"

  - alert: high_disk_usage_c_drive_windows
    expr: '((wmi_logical_disk_size_bytes{volume="C:"} - wmi_logical_disk_free_bytes{volume="C:"}) / wmi_logical_disk_size_bytes{volume="C:"} * 100) > 95'
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has high disk usage
        (above 95% (current value is {{$value}})) on the system volume for more than
        5 minutes.'
      summary: 'Instance {{$labels.instance}} with high disk usage on the system volume'

  - alert: high_disk_usage_d_drive_windows
    expr: '((wmi_logical_disk_size_bytes{volume="D:"} - wmi_logical_disk_free_bytes{volume="D:"}) / wmi_logical_disk_size_bytes{volume="D:"} * 100) > 95'
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has high disk usage
        (above 95% (current value is {{$value}})) on the system volume for more than
        5 minutes.'
      summary: 'Instance {{$labels.instance}} with high disk usage on the system volume'

  - alert: high_disk_usage_e_drive_windows
    expr: '((wmi_logical_disk_size_bytes{volume="E:"} - wmi_logical_disk_free_bytes{volume="E:"}) / wmi_logical_disk_size_bytes{volume="E:"} * 100) > 95'
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has high disk usage
        (above 80% (current value is {{$value}})) on the system volume for more than
        5 minutes.'
      summary: 'Instance {{$labels.instance}} with high disk usage on the system volume'

  - alert: high_cpu_usage_windows
    expr: '100 - (avg by (instance) (rate(wmi_cpu_time_total{mode="idle"}[1h])) * 100) > 95'
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has high CPU usage
        (above 95% (current value is {{$value}})) on the system volume for more than
        5 minutes.'
      summary: 'Instance {{$labels.instance}} with high CPU usage on the system volume'


- name: SSL_Expired
  rules:
  - alert: SSL_Certificate_Expired
    expr: probe_ssl_earliest_cert_expiry < time()
    labels:
      severity: Critical
    annotations:
      summary: "alert from docker-prometheus SSL certificate for {{ $labels.instance }} expired"
      description: "The SSL certificate for {{ $labels.instance }} expired and needs immediate attention."
      
- name: SSL_Expiry
  rules:
  - alert: SSL_Certificate_Expiring_Soon
    expr: (probe_ssl_earliest_cert_expiry - time()) < 86400 * 30 and (probe_ssl_earliest_cert_expiry > time())
    labels:
      severity: High
    annotations:
      summary: "alert from docker-prometheus SSL certificate for {{ $labels.instance }} is expiring soon"
      description: "The SSL certificate for {{ $labels.instance }} will expire in less than 30 days."

- name: login_alerts
  rules:
  - alert: LoginUnsuccessful
    expr: login_success == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Login Unsuccessful for {{ $labels.url }}"
      description: "Login to {{ $labels.url }} has been unsuccessful for more than 5 minutes."

- name: tcp_connectivity
  rules:
  - alert: TCPConnectivityDown
    expr: tcp_connectivity_check == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "TCP connectivity to {{ $labels.target }}:{{ $labels.port }} is down"
      description: "Unable to establish a TCP connection to {{ $labels.target }}:{{ $labels.port }} for more than 1 minute."
      
- name: ephemeral_port_exhaustion
  rules:
  - alert: EphemeralPortExhaustion
    expr: available_ephemeral_ports_count < 3000
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Ephemeral port exhaustion detected"
      description: >
        The number of available ephemeral ports has dropped below 3000.
        Current available ports: {{ $value }}
        Ephemeral port range: {{ $labels.range }}
        This may lead to TCP connection failures if not addressed promptly.

- name: ephemeral_port_exhausted
  rules:
  - alert: EphemeralPorts Exhausted
    expr: available_ephemeral_ports_count < 1
    for: 1m
    labels:
      severity: Critical
    annotations:
      summary: "Ephemeral port exhausted"
      description: >
        Ephemeral ports exhausted.
        Current available ports: {{ $value }}
        Application will not be able to make TCP connections.
