FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY cmmonitoring.moslof.com.pem /etc/nginx/ssl/cmmonitoring.moslof.com.pem
COPY cmmonitoring.moslof.com.key /etc/nginx/ssl/cmmonitoring.moslof.com.key
